parent:
    github:         hiqdev/hidev-config

package:
    name:           hidev-php-cs-fixer
    namespace:      hidev\phpcsfixer
    label:          HiDev PhpCSFixer
    title:          PHP Coding Standards Fixer Plugin for HiPanel
    type:           yii2-extension
    keywords:       php-cs-fixer, hidev, plugin
    year:           2015

composer.json:
    require:
        hiqdev/hidev:       '*@dev'

