package:
    type:           yii2-extension
    name:           hidev-php-cs-fixer
    title:          PHP-CS-Fixer plugin for HiDev
    headline:       HiDev PHP-CS-Fixer
    keywords:       php-cs-fixer, hidev, plugin
    namespace:      hidev\phpcsfixer
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin enables [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) support for HiDev.

        Provides:
        - writing `.php_cs` config file
        - running php-cs-fixer from proper path

        ### Renamed fixers v1 -> v2

        - multiline_spaces_before_semicolon -> no_multiline_whitespace_before_semicolons
        - newline_after_open_tag -> ?
        - blankline_after_open_tag -> blank_line_after_opening_tag
        - ordered_use -> ordered_imports
        - strict -> strict_comparison
