package:
    name:           hidev-php-cs-fixer
    namespace:      hidev\phpcsfixer
    label:          HiDev PhpCSFixer
    title:          php-cs-fixer plugin for HiDev
    type:           yii2-extension
    keywords:       php-cs-fixer, hidev, plugin
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
